// SPDX-FileCopyrightText: 2026 VisorCraft LLC
// SPDX-License-Identifier: GPL-3.0-only

// Licenses page — three tabs (LinSight License / Third-party /
// Acknowledgments) over a single filterable monospaced viewer.
// Mirrors Grexa's LicensesPage anatomy: tab bar, doc title +
// subtitle, find/wrap/copy strip, document body. The bodies come
// from `OverviewModel` (`gpl_text`, `credits_text` = cargo-about
// output, `narrative_credits_text` = CREDITS.md).

import QtQuick
import QtQuick.Controls as Controls
import QtQuick.Layouts
import org.kde.kirigami as Kirigami

Kirigami.Page {
    id: page
    padding: 0
    titleDelegate: Item {}
    globalToolBarStyle: Kirigami.ApplicationHeaderStyle.None

    signal gplTextRequested()

    // Shared OverviewModel — passes the bundled-at-build-time
    // documents through invokables (qrc:/ XHR isn't reliable for
    // local resources, so we route through Q_INVOKABLE getters).
    property QtObject dashModel: null

    property int activeDocument: 0
    property string filterText: ""
    property bool wrapText: false

    readonly property string gplText: page.dashModel
        ? page.dashModel.gplText() : ""
    readonly property string thirdPartyText: page.dashModel
        ? page.dashModel.creditsText() : ""
    readonly property string acknowledgmentsText: page.dashModel
        ? page.dashModel.narrativeCreditsText() : ""

    readonly property string currentTitle: page.documentTitle(page.activeDocument)
    readonly property string currentSubtitle: page.documentSubtitle(page.activeDocument)
    readonly property string currentBody: page.documentBody(page.activeDocument)
    readonly property int currentLineCount: page.lineCount(page.currentBody)
    readonly property int matchingLineCount:
        page.countMatchingLines(page.currentBody, page.filterText)
    readonly property string visibleBody:
        page.filteredBody(page.currentBody, page.filterText)

    Kirigami.Theme.inherit: false
    Kirigami.Theme.colorSet: Kirigami.Theme.View
    Kirigami.Theme.backgroundColor: app.tokens.surface0
    Kirigami.Theme.textColor: app.tokens.textPrimary
    Kirigami.Theme.highlightColor: app.tokens.accent
    Kirigami.Theme.highlightedTextColor: app.tokens.accentText

    background: Rectangle { color: app.tokens.surface0 }

    function documentTitle(idx) {
        switch (idx) {
        case 1: return qsTr("Third-party licenses")
        case 2: return qsTr("Acknowledgments")
        default: return qsTr("LinSight License")
        }
    }
    function documentSubtitle(idx) {
        switch (idx) {
        case 1:
            return qsTr("Auto-generated by cargo-about from Cargo.lock. Every direct and transitive crate, grouped by license text.")
        case 2:
            return qsTr("Curated attribution for the runtime components and direct crate dependencies.")
        default:
            return qsTr("LinSight is distributed under GPL-3.0-only; the full license text is bundled into the binary.")
        }
    }
    function documentBody(idx) {
        switch (idx) {
        case 1: return page.thirdPartyText
        case 2: return page.acknowledgmentsText
        default: return page.gplText
        }
    }

    function lineCount(text) {
        if (!text || text.length === 0) return 0
        return String(text).split("\n").length
    }
    function lineNumber(value) {
        let s = String(value)
        while (s.length < 5) s = " " + s
        return s
    }
    function countMatchingLines(text, query) {
        const needle = String(query).trim().toLowerCase()
        if (needle.length === 0) return 0
        const lines = String(text).split("\n")
        let matches = 0
        for (let i = 0; i < lines.length; ++i) {
            if (lines[i].toLowerCase().indexOf(needle) !== -1) matches += 1
        }
        return matches
    }
    function filteredBody(text, query) {
        const source = String(text)
        const needle = String(query).trim().toLowerCase()
        if (needle.length === 0) return source
        const lines = source.split("\n")
        const matches = []
        for (let i = 0; i < lines.length; ++i) {
            if (lines[i].toLowerCase().indexOf(needle) !== -1) {
                matches.push(page.lineNumber(i + 1) + "  " + lines[i])
            }
        }
        if (matches.length === 0) return qsTr("No matches for \"%1\".").arg(query)
        return matches.join("\n")
    }

    function setActiveDocument(idx) {
        if (page.activeDocument === idx) return
        page.activeDocument = idx
        page.filterText = ""
        filterField.text = ""
    }

    // QClipboard isn't exposed through cxx-qt-lib, so we copy by
    // pushing the body into a hidden TextEdit, selecting it all,
    // and calling its built-in `copy()`. Costs nothing visually and
    // keeps the bridge surface unchanged.
    TextEdit {
        id: clipboardProxy
        visible: false
        readOnly: true
        function pushAndCopy(text) {
            clipboardProxy.text = text
            clipboardProxy.selectAll()
            clipboardProxy.copy()
        }
    }

    ColumnLayout {
        anchors.fill: parent
        spacing: 0

        // -- Page header ------------------------------------------
        Rectangle {
            Layout.fillWidth: true
            Layout.preferredHeight: 86
            color: app.tokens.surface1
            Rectangle {
                anchors.left: parent.left
                anchors.right: parent.right
                anchors.bottom: parent.bottom
                height: 1
                color: app.tokens.separator
            }
            ColumnLayout {
                anchors.fill: parent
                anchors.leftMargin: app.tokens.spaceXL
                anchors.rightMargin: app.tokens.spaceXL
                spacing: app.tokens.spaceXS
                Item { Layout.fillHeight: true }
                Controls.Label {
                    text: qsTr("Licenses")
                    color: app.tokens.textPrimary
                    font.pixelSize: 24
                    font.weight: app.tokens.weightBold
                    font.family: app.tokens.sansFamily
                    Layout.fillWidth: true
                }
                Controls.Label {
                    text: qsTr("Bundled license and attribution documents — searchable without leaving the app.")
                    color: app.tokens.textPrimary
                    font.pixelSize: app.tokens.textCaption + 1
                    font.family: app.tokens.sansFamily
                    opacity: 0.62
                    Layout.fillWidth: true
                    elide: Text.ElideRight
                }
                Item { Layout.fillHeight: true }
            }
        }

        // -- Body -------------------------------------------------
        ColumnLayout {
            Layout.fillWidth: true
            Layout.fillHeight: true
            Layout.leftMargin: app.tokens.spaceXL
            Layout.rightMargin: app.tokens.spaceXL
            Layout.topMargin: app.tokens.spaceL
            Layout.bottomMargin: app.tokens.spaceXL
            spacing: app.tokens.spaceM

            // Tab bar + Copy + Dialog
            RowLayout {
                Layout.fillWidth: true
                spacing: app.tokens.spaceM
                Controls.TabBar {
                    id: tabs
                    Layout.fillWidth: true
                    currentIndex: page.activeDocument
                    onCurrentIndexChanged: page.setActiveDocument(currentIndex)
                    Controls.TabButton {
                        text: qsTr("LinSight License")
                        width: implicitWidth + app.tokens.spaceL
                    }
                    Controls.TabButton {
                        text: qsTr("Third-party")
                        width: implicitWidth + app.tokens.spaceL
                    }
                    Controls.TabButton {
                        text: qsTr("Acknowledgments")
                        width: implicitWidth + app.tokens.spaceL
                    }
                }
                Controls.Button {
                    text: qsTr("Copy")
                    icon.name: "edit-copy-symbolic"
                    display: Controls.AbstractButton.TextBesideIcon
                    onClicked: clipboardProxy.pushAndCopy(page.currentBody)
                    Controls.ToolTip.text: qsTr("Copy the current document")
                    Controls.ToolTip.visible: hovered
                }
                Controls.Button {
                    visible: page.activeDocument === 0
                    text: qsTr("Dialog")
                    icon.name: "document-preview-symbolic"
                    display: Controls.AbstractButton.TextBesideIcon
                    onClicked: page.gplTextRequested()
                    Controls.ToolTip.text: qsTr("Open the GPL text in a dialog")
                    Controls.ToolTip.visible: hovered
                }
            }

            // Doc title + subtitle + line count
            RowLayout {
                Layout.fillWidth: true
                spacing: app.tokens.spaceM
                ColumnLayout {
                    Layout.fillWidth: true
                    spacing: app.tokens.spaceXS
                    Controls.Label {
                        text: page.currentTitle
                        color: app.tokens.textPrimary
                        font.pixelSize: app.tokens.textSubheading
                        font.weight: app.tokens.weightBold
                        font.family: app.tokens.sansFamily
                        Layout.fillWidth: true
                    }
                    Controls.Label {
                        text: page.currentSubtitle
                        color: app.tokens.textPrimary
                        font.pixelSize: app.tokens.textCaption + 1
                        font.family: app.tokens.sansFamily
                        opacity: 0.62
                        wrapMode: Text.WordWrap
                        Layout.fillWidth: true
                    }
                }
                Controls.Label {
                    text: page.filterText.trim().length > 0
                        ? qsTr("%1 matches").arg(page.matchingLineCount)
                        : qsTr("%1 lines").arg(page.currentLineCount)
                    color: app.tokens.textPrimary
                    font.pixelSize: app.tokens.textCaption
                    font.family: app.tokens.monoFamily
                    opacity: 0.62
                    Layout.alignment: Qt.AlignRight | Qt.AlignVCenter
                }
            }

            // Find + Wrap + Clear
            RowLayout {
                Layout.fillWidth: true
                spacing: app.tokens.spaceS
                Controls.TextField {
                    id: filterField
                    Layout.fillWidth: true
                    placeholderText: qsTr("Find by crate, package, license, or phrase…")
                    onTextChanged: page.filterText = text
                    Accessible.name: qsTr("Find in license document")
                }
                Controls.CheckBox {
                    text: qsTr("Wrap")
                    checked: page.wrapText
                    onToggled: page.wrapText = checked
                }
                Controls.Button {
                    enabled: page.filterText.length > 0
                    text: qsTr("Clear")
                    icon.name: "edit-clear-symbolic"
                    display: Controls.AbstractButton.TextBesideIcon
                    onClicked: {
                        filterField.text = ""
                        page.filterText = ""
                    }
                }
            }

            // Document viewer
            Rectangle {
                Layout.fillWidth: true
                Layout.fillHeight: true
                Layout.minimumHeight: 340
                radius: app.tokens.radiusCard
                color: app.tokens.surface1
                border.color: app.tokens.separator
                border.width: 1
                clip: true

                Controls.ScrollView {
                    anchors.fill: parent
                    anchors.margins: app.tokens.spaceM
                    clip: true
                    Controls.TextArea {
                        id: documentArea
                        text: page.visibleBody
                        readOnly: true
                        selectByMouse: true
                        persistentSelection: true
                        wrapMode: page.wrapText ? TextEdit.Wrap : TextEdit.NoWrap
                        textFormat: TextEdit.PlainText
                        color: app.tokens.textPrimary
                        selectedTextColor: app.tokens.accentText
                        selectionColor: app.tokens.accent
                        font.pixelSize: app.tokens.textCaption + 1
                        font.family: app.tokens.monoFamily
                        background: Rectangle { color: "transparent" }
                    }
                }
            }
        }
    }
}
